version: '3.8'
services:
  # eAi Application
  eai-app:
    image: docform:latest
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://eai-mysql:3306/docform?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - AWS_S3_ACCESS_KEY=${AWS_ACCESS_KEY:-your_access_key}
      - AWS_S3_SECRET_KEY=${AWS_SECRET_KEY:-your_secret_key}
      - SPRING_CLOUD_CONSUL_ENABLED=false
      - GEMINI_API_KEY=${GEMINI_API_KEY:-your_gemini_key}
    ports:
      - "8084:8084"
    depends_on:
      eai-mysql:
        condition: service_healthy

  # MySQL Database
  eai-mysql:
    image: mysql:9.2.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=docform
    ports:
      - "3021:3306"
    command: mysqld --lower_case_table_names=1 --skip-mysqlx --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
