CREATE DATABASE IF NOT EXISTS eaccount CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS eform CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS eflow CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS erequest CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS docform CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON eaccount.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON eform.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON eflow.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON erequest.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON docform.* TO 'root'@'%';
FLUSH PRIVILEGES;
