services:
  - name: eform
    type: web
    runtime: docker
    rootDir: eForm
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: DEMO_MODE
        value: "true"
      - key: JHIPSTER_CORS_ALLOWED_ORIGINS
        value: https://datawarehouse-subject.web.app
      - key: JHIPSTER_CORS_ALLOWED_METHODS
        value: "*"
      - key: JHIPSTER_CORS_ALLOWED_HEADERS
        value: "*"
      - key: JHIPSTER_CORS_ALLOW_CREDENTIALS
        value: "true"
      - key: JHIPSTER_CORS_MAX_AGE
        value: "1800"
    healthCheckPath: /api/owner/menu-views

  - name: eflow
    type: web
    runtime: docker
    rootDir: eFlow
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: DEMO_MODE
        value: "true"
      - key: JHIPSTER_CORS_ALLOWED_ORIGINS
        value: https://datawarehouse-subject.web.app
      - key: JHIPSTER_CORS_ALLOWED_METHODS
        value: "*"
      - key: JHIPSTER_CORS_ALLOWED_HEADERS
        value: "*"
      - key: JHIPSTER_CORS_ALLOW_CREDENTIALS
        value: "true"
      - key: JHIPSTER_CORS_MAX_AGE
        value: "1800"
      - key: APPLICATION_CLIENT_EFORM_URL
        value: https://eform.onrender.com
    healthCheckPath: /api/workflow/1/summary

  - name: erequest
    type: web
    runtime: docker
    rootDir: eRequest
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: DEMO_MODE
        value: "true"
      - key: JHIPSTER_CORS_ALLOWED_ORIGINS
        value: https://datawarehouse-subject.web.app
      - key: JHIPSTER_CORS_ALLOWED_METHODS
        value: "*"
      - key: JHIPSTER_CORS_ALLOWED_HEADERS
        value: "*"
      - key: JHIPSTER_CORS_ALLOW_CREDENTIALS
        value: "true"
      - key: JHIPSTER_CORS_MAX_AGE
        value: "1800"
      - key: APPLICATION_CLIENT_EFLOW_URL
        value: https://eflow.onrender.com
    healthCheckPath: /api/request/workflows
