package com.vnu.uet.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentExtractionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentExtractionAllPropertiesEquals(DocumentExtraction expected, DocumentExtraction actual) {
        assertDocumentExtractionAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentExtractionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentExtractionAllUpdatablePropertiesEquals(DocumentExtraction expected, DocumentExtraction actual) {
        assertDocumentExtractionUpdatableFieldsEquals(expected, actual);
        assertDocumentExtractionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentExtractionAutoGeneratedPropertiesEquals(DocumentExtraction expected, DocumentExtraction actual) {
        assertThat(actual)
            .as("Verify DocumentExtraction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentExtractionUpdatableFieldsEquals(DocumentExtraction expected, DocumentExtraction actual) {
        assertThat(actual)
            .as("Verify DocumentExtraction relevant properties")
            .satisfies(a -> assertThat(a.gets3Key()).as("check s3Key").isEqualTo(expected.gets3Key()))
            .satisfies(a -> assertThat(a.getFormName()).as("check formName").isEqualTo(expected.getFormName()))
            .satisfies(a -> assertThat(a.getRawText()).as("check rawText").isEqualTo(expected.getRawText()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getExtractedAt()).as("check extractedAt").isEqualTo(expected.getExtractedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentExtractionUpdatableRelationshipsEquals(DocumentExtraction expected, DocumentExtraction actual) {
        // empty method
    }
}
