package com.vnu.uet.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FilledFormAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFilledFormAllPropertiesEquals(FilledForm expected, FilledForm actual) {
        assertFilledFormAutoGeneratedPropertiesEquals(expected, actual);
        assertFilledFormAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFilledFormAllUpdatablePropertiesEquals(FilledForm expected, FilledForm actual) {
        assertFilledFormUpdatableFieldsEquals(expected, actual);
        assertFilledFormUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFilledFormAutoGeneratedPropertiesEquals(FilledForm expected, FilledForm actual) {
        assertThat(actual)
            .as("Verify FilledForm auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFilledFormUpdatableFieldsEquals(FilledForm expected, FilledForm actual) {
        assertThat(actual)
            .as("Verify FilledForm relevant properties")
            .satisfies(a -> assertThat(a.getFormName()).as("check formName").isEqualTo(expected.getFormName()))
            .satisfies(a -> assertThat(a.getFilledData()).as("check filledData").isEqualTo(expected.getFilledData()))
            .satisfies(a -> assertThat(a.getConfidence()).as("check confidence").isEqualTo(expected.getConfidence()))
            .satisfies(a -> assertThat(a.getGeminiModel()).as("check geminiModel").isEqualTo(expected.getGeminiModel()))
            .satisfies(a -> assertThat(a.getProcessedAt()).as("check processedAt").isEqualTo(expected.getProcessedAt()))
            .satisfies(a -> assertThat(a.getMissingFields()).as("check missingFields").isEqualTo(expected.getMissingFields()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFilledFormUpdatableRelationshipsEquals(FilledForm expected, FilledForm actual) {
        assertThat(actual)
            .as("Verify FilledForm relationships")
            .satisfies(a -> assertThat(a.getDocument()).as("check document").isEqualTo(expected.getDocument()));
    }
}
