package com.vnu.uet.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FlowAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlowAllPropertiesEquals(Flow expected, Flow actual) {
        assertFlowAutoGeneratedPropertiesEquals(expected, actual);
        assertFlowAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlowAllUpdatablePropertiesEquals(Flow expected, Flow actual) {
        assertFlowUpdatableFieldsEquals(expected, actual);
        assertFlowUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlowAutoGeneratedPropertiesEquals(Flow expected, Flow actual) {
        assertThat(expected)
            .as("Verify Flow auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlowUpdatableFieldsEquals(Flow expected, Flow actual) {
        assertThat(expected)
            .as("Verify Flow relevant properties")
            .satisfies(e -> assertThat(e.getFlowName()).as("check flowName").isEqualTo(actual.getFlowName()))
            .satisfies(e -> assertThat(e.getFlowGroup()).as("check flowGroup").isEqualTo(actual.getFlowGroup()))
            .satisfies(e -> assertThat(e.getOwnerName()).as("check ownerName").isEqualTo(actual.getOwnerName()))
            .satisfies(e -> assertThat(e.getSuperviserName()).as("check superviserName").isEqualTo(actual.getSuperviserName()))
            .satisfies(e -> assertThat(e.getDepartment()).as("check department").isEqualTo(actual.getDepartment()))
            .satisfies(e -> assertThat(e.getDescribe()).as("check describe").isEqualTo(actual.getDescribe()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getFlowStartDate()).as("check flowStartDate").isEqualTo(actual.getFlowStartDate()))
            .satisfies(e -> assertThat(e.getFlowEndDate()).as("check flowEndDate").isEqualTo(actual.getFlowEndDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlowUpdatableRelationshipsEquals(Flow expected, Flow actual) {
        // empty method
    }
}
