package com.vnu.uet.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MapFormAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMapFormAllPropertiesEquals(MapForm expected, MapForm actual) {
        assertMapFormAutoGeneratedPropertiesEquals(expected, actual);
        assertMapFormAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMapFormAllUpdatablePropertiesEquals(MapForm expected, MapForm actual) {
        assertMapFormUpdatableFieldsEquals(expected, actual);
        assertMapFormUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMapFormAutoGeneratedPropertiesEquals(MapForm expected, MapForm actual) {
        assertThat(expected)
            .as("Verify MapForm auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMapFormUpdatableFieldsEquals(MapForm expected, MapForm actual) {
        assertThat(expected)
            .as("Verify MapForm relevant properties")
            .satisfies(e -> assertThat(e.getTargetFormId()).as("check targetFormId").isEqualTo(actual.getTargetFormId()))
            .satisfies(e -> assertThat(e.getSourceFormId()).as("check sourceFormId").isEqualTo(actual.getSourceFormId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMapFormUpdatableRelationshipsEquals(MapForm expected, MapForm actual) {
        assertThat(expected)
            .as("Verify MapForm relationships")
            .satisfies(e -> assertThat(e.getNode()).as("check node").isEqualTo(actual.getNode()));
    }
}
