package com.vnu.uet.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NodeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeAllPropertiesEquals(Node expected, Node actual) {
        assertNodeAutoGeneratedPropertiesEquals(expected, actual);
        assertNodeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeAllUpdatablePropertiesEquals(Node expected, Node actual) {
        assertNodeUpdatableFieldsEquals(expected, actual);
        assertNodeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeAutoGeneratedPropertiesEquals(Node expected, Node actual) {
        assertThat(expected)
            .as("Verify Node auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeUpdatableFieldsEquals(Node expected, Node actual) {
        assertThat(expected)
            .as("Verify Node relevant properties")
            .satisfies(e -> assertThat(e.getNodeType()).as("check nodeType").isEqualTo(actual.getNodeType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeUpdatableRelationshipsEquals(Node expected, Node actual) {
        assertThat(expected)
            .as("Verify Node relationships")
            .satisfies(e -> assertThat(e.getFlow()).as("check flow").isEqualTo(actual.getFlow()));
    }
}
