package com.vnu.uet.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PerformerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerformerAllPropertiesEquals(Performer expected, Performer actual) {
        assertPerformerAutoGeneratedPropertiesEquals(expected, actual);
        assertPerformerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerformerAllUpdatablePropertiesEquals(Performer expected, Performer actual) {
        assertPerformerUpdatableFieldsEquals(expected, actual);
        assertPerformerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerformerAutoGeneratedPropertiesEquals(Performer expected, Performer actual) {
        assertThat(expected)
            .as("Verify Performer auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerformerUpdatableFieldsEquals(Performer expected, Performer actual) {
        assertThat(expected)
            .as("Verify Performer relevant properties")
            .satisfies(e -> assertThat(e.getUserId()).as("check userId").isEqualTo(actual.getUserId()))
            .satisfies(e -> assertThat(e.getOrderExecution()).as("check orderExecution").isEqualTo(actual.getOrderExecution()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerformerUpdatableRelationshipsEquals(Performer expected, Performer actual) {
        assertThat(expected)
            .as("Verify Performer relationships")
            .satisfies(e -> assertThat(e.getNode()).as("check node").isEqualTo(actual.getNode()));
    }
}
