package com.vnu.uet.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RelateDemandAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRelateDemandAllPropertiesEquals(RelateDemand expected, RelateDemand actual) {
        assertRelateDemandAutoGeneratedPropertiesEquals(expected, actual);
        assertRelateDemandAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRelateDemandAllUpdatablePropertiesEquals(RelateDemand expected, RelateDemand actual) {
        assertRelateDemandUpdatableFieldsEquals(expected, actual);
        assertRelateDemandUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRelateDemandAutoGeneratedPropertiesEquals(RelateDemand expected, RelateDemand actual) {
        assertThat(expected)
            .as("Verify RelateDemand auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRelateDemandUpdatableFieldsEquals(RelateDemand expected, RelateDemand actual) {
        assertThat(expected)
            .as("Verify RelateDemand relevant properties")
            .satisfies(e -> assertThat(e.getRelateDemand()).as("check relateDemand").isEqualTo(actual.getRelateDemand()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRelateDemandUpdatableRelationshipsEquals(RelateDemand expected, RelateDemand actual) {
        assertThat(expected)
            .as("Verify RelateDemand relationships")
            .satisfies(e -> assertThat(e.getRelateNode()).as("check relateNode").isEqualTo(actual.getRelateNode()))
            .satisfies(e -> assertThat(e.getSwitchNode()).as("check switchNode").isEqualTo(actual.getSwitchNode()));
    }
}
