package com.vnu.uet.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RelateNodeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRelateNodeAllPropertiesEquals(RelateNode expected, RelateNode actual) {
        assertRelateNodeAutoGeneratedPropertiesEquals(expected, actual);
        assertRelateNodeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRelateNodeAllUpdatablePropertiesEquals(RelateNode expected, RelateNode actual) {
        assertRelateNodeUpdatableFieldsEquals(expected, actual);
        assertRelateNodeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRelateNodeAutoGeneratedPropertiesEquals(RelateNode expected, RelateNode actual) {
        assertThat(expected)
            .as("Verify RelateNode auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRelateNodeUpdatableFieldsEquals(RelateNode expected, RelateNode actual) {
        assertThat(expected)
            .as("Verify RelateNode relevant properties")
            .satisfies(e -> assertThat(e.getHasDemand()).as("check hasDemand").isEqualTo(actual.getHasDemand()))
            .satisfies(e -> assertThat(e.getChildNodeId()).as("check childNodeId").isEqualTo(actual.getChildNodeId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRelateNodeUpdatableRelationshipsEquals(RelateNode expected, RelateNode actual) {
        assertThat(expected)
            .as("Verify RelateNode relationships")
            .satisfies(e -> assertThat(e.getFlow()).as("check flow").isEqualTo(actual.getFlow()))
            .satisfies(e -> assertThat(e.getNode()).as("check node").isEqualTo(actual.getNode()));
    }
}
