package com.vnu.uet.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SwitchNodeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSwitchNodeAllPropertiesEquals(SwitchNode expected, SwitchNode actual) {
        assertSwitchNodeAutoGeneratedPropertiesEquals(expected, actual);
        assertSwitchNodeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSwitchNodeAllUpdatablePropertiesEquals(SwitchNode expected, SwitchNode actual) {
        assertSwitchNodeUpdatableFieldsEquals(expected, actual);
        assertSwitchNodeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSwitchNodeAutoGeneratedPropertiesEquals(SwitchNode expected, SwitchNode actual) {
        assertThat(expected)
            .as("Verify SwitchNode auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSwitchNodeUpdatableFieldsEquals(SwitchNode expected, SwitchNode actual) {
        assertThat(expected)
            .as("Verify SwitchNode relevant properties")
            .satisfies(e -> assertThat(e.getFormId()).as("check formId").isEqualTo(actual.getFormId()))
            .satisfies(e -> assertThat(e.getVariableId()).as("check variableId").isEqualTo(actual.getVariableId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSwitchNodeUpdatableRelationshipsEquals(SwitchNode expected, SwitchNode actual) {
        assertThat(expected)
            .as("Verify SwitchNode relationships")
            .satisfies(e -> assertThat(e.getFlow()).as("check flow").isEqualTo(actual.getFlow()))
            .satisfies(e -> assertThat(e.getRelateNode()).as("check relateNode").isEqualTo(actual.getRelateNode()));
    }
}
