package com.vnu.uet.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VariableAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVariableAllPropertiesEquals(Variable expected, Variable actual) {
        assertVariableAutoGeneratedPropertiesEquals(expected, actual);
        assertVariableAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVariableAllUpdatablePropertiesEquals(Variable expected, Variable actual) {
        assertVariableUpdatableFieldsEquals(expected, actual);
        assertVariableUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVariableAutoGeneratedPropertiesEquals(Variable expected, Variable actual) {
        assertThat(expected)
            .as("Verify Variable auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVariableUpdatableFieldsEquals(Variable expected, Variable actual) {
        assertThat(expected)
            .as("Verify Variable relevant properties")
            .satisfies(e ->
                assertThat(e.getVariableSourceFormId()).as("check variableSourceFormId").isEqualTo(actual.getVariableSourceFormId())
            )
            .satisfies(e ->
                assertThat(e.getVariableTargetFormId()).as("check variableTargetFormId").isEqualTo(actual.getVariableTargetFormId())
            )
            .satisfies(e -> assertThat(e.getFormula()).as("check formula").isEqualTo(actual.getFormula()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVariableUpdatableRelationshipsEquals(Variable expected, Variable actual) {
        assertThat(expected)
            .as("Verify Variable relationships")
            .satisfies(e -> assertThat(e.getMapForm()).as("check mapForm").isEqualTo(actual.getMapForm()));
    }
}
