package com.mycompany.erequest.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TicketCommentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketCommentAllPropertiesEquals(TicketComment expected, TicketComment actual) {
        assertTicketCommentAutoGeneratedPropertiesEquals(expected, actual);
        assertTicketCommentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketCommentAllUpdatablePropertiesEquals(TicketComment expected, TicketComment actual) {
        assertTicketCommentUpdatableFieldsEquals(expected, actual);
        assertTicketCommentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketCommentAutoGeneratedPropertiesEquals(TicketComment expected, TicketComment actual) {
        assertThat(expected)
            .as("Verify TicketComment auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketCommentUpdatableFieldsEquals(TicketComment expected, TicketComment actual) {
        assertThat(expected)
            .as("Verify TicketComment relevant properties")
            .satisfies(e -> assertThat(e.getAuthorEmail()).as("check authorEmail").isEqualTo(actual.getAuthorEmail()))
            .satisfies(e -> assertThat(e.getContent()).as("check content").isEqualTo(actual.getContent()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketCommentUpdatableRelationshipsEquals(TicketComment expected, TicketComment actual) {
        assertThat(expected)
            .as("Verify TicketComment relationships")
            .satisfies(e -> assertThat(e.getTicket()).as("check ticket").isEqualTo(actual.getTicket()));
    }
}
