package com.mycompany.erequest.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TicketDataLinkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketDataLinkAllPropertiesEquals(TicketDataLink expected, TicketDataLink actual) {
        assertTicketDataLinkAutoGeneratedPropertiesEquals(expected, actual);
        assertTicketDataLinkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketDataLinkAllUpdatablePropertiesEquals(TicketDataLink expected, TicketDataLink actual) {
        assertTicketDataLinkUpdatableFieldsEquals(expected, actual);
        assertTicketDataLinkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketDataLinkAutoGeneratedPropertiesEquals(TicketDataLink expected, TicketDataLink actual) {
        assertThat(expected)
            .as("Verify TicketDataLink auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketDataLinkUpdatableFieldsEquals(TicketDataLink expected, TicketDataLink actual) {
        assertThat(expected)
            .as("Verify TicketDataLink relevant properties")
            .satisfies(e -> assertThat(e.getNodeId()).as("check nodeId").isEqualTo(actual.getNodeId()))
            .satisfies(e -> assertThat(e.getFormDataId()).as("check formDataId").isEqualTo(actual.getFormDataId()))
            .satisfies(e -> assertThat(e.getParentFormDataId()).as("check parentFormDataId").isEqualTo(actual.getParentFormDataId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketDataLinkUpdatableRelationshipsEquals(TicketDataLink expected, TicketDataLink actual) {
        assertThat(expected)
            .as("Verify TicketDataLink relationships")
            .satisfies(e -> assertThat(e.getTicket()).as("check ticket").isEqualTo(actual.getTicket()));
    }
}
