package com.mycompany.erequest.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TicketRelationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketRelationAllPropertiesEquals(TicketRelation expected, TicketRelation actual) {
        assertTicketRelationAutoGeneratedPropertiesEquals(expected, actual);
        assertTicketRelationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketRelationAllUpdatablePropertiesEquals(TicketRelation expected, TicketRelation actual) {
        assertTicketRelationUpdatableFieldsEquals(expected, actual);
        assertTicketRelationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketRelationAutoGeneratedPropertiesEquals(TicketRelation expected, TicketRelation actual) {
        assertThat(expected)
            .as("Verify TicketRelation auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketRelationUpdatableFieldsEquals(TicketRelation expected, TicketRelation actual) {
        assertThat(expected)
            .as("Verify TicketRelation relevant properties")
            .satisfies(e -> assertThat(e.getRelatedTicketId()).as("check relatedTicketId").isEqualTo(actual.getRelatedTicketId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketRelationUpdatableRelationshipsEquals(TicketRelation expected, TicketRelation actual) {
        assertThat(expected)
            .as("Verify TicketRelation relationships")
            .satisfies(e -> assertThat(e.getTicket()).as("check ticket").isEqualTo(actual.getTicket()));
    }
}
