package com.mycompany.erequest.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TicketAttachmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketAttachmentAllPropertiesEquals(TicketAttachment expected, TicketAttachment actual) {
        assertTicketAttachmentAutoGeneratedPropertiesEquals(expected, actual);
        assertTicketAttachmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketAttachmentAllUpdatablePropertiesEquals(TicketAttachment expected, TicketAttachment actual) {
        assertTicketAttachmentUpdatableFieldsEquals(expected, actual);
        assertTicketAttachmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketAttachmentAutoGeneratedPropertiesEquals(TicketAttachment expected, TicketAttachment actual) {
        assertThat(expected)
            .as("Verify TicketAttachment auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketAttachmentUpdatableFieldsEquals(TicketAttachment expected, TicketAttachment actual) {
        assertThat(expected)
            .as("Verify TicketAttachment relevant properties")
            .satisfies(e -> assertThat(e.getFileId()).as("check fileId").isEqualTo(actual.getFileId()))
            .satisfies(e -> assertThat(e.getFileName()).as("check fileName").isEqualTo(actual.getFileName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketAttachmentUpdatableRelationshipsEquals(TicketAttachment expected, TicketAttachment actual) {
        assertThat(expected)
            .as("Verify TicketAttachment relationships")
            .satisfies(e -> assertThat(e.getTicket()).as("check ticket").isEqualTo(actual.getTicket()));
    }
}
