package com.mycompany.erequest.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TicketStepAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketStepAllPropertiesEquals(TicketStep expected, TicketStep actual) {
        assertTicketStepAutoGeneratedPropertiesEquals(expected, actual);
        assertTicketStepAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketStepAllUpdatablePropertiesEquals(TicketStep expected, TicketStep actual) {
        assertTicketStepUpdatableFieldsEquals(expected, actual);
        assertTicketStepUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketStepAutoGeneratedPropertiesEquals(TicketStep expected, TicketStep actual) {
        assertThat(expected)
            .as("Verify TicketStep auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketStepUpdatableFieldsEquals(TicketStep expected, TicketStep actual) {
        assertThat(expected)
            .as("Verify TicketStep relevant properties")
            .satisfies(e -> assertThat(e.getNodeId()).as("check nodeId").isEqualTo(actual.getNodeId()))
            .satisfies(e -> assertThat(e.getPerformerEmail()).as("check performerEmail").isEqualTo(actual.getPerformerEmail()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getStartedAt()).as("check startedAt").isEqualTo(actual.getStartedAt()))
            .satisfies(e -> assertThat(e.getFinishedAt()).as("check finishedAt").isEqualTo(actual.getFinishedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketStepUpdatableRelationshipsEquals(TicketStep expected, TicketStep actual) {
        assertThat(expected)
            .as("Verify TicketStep relationships")
            .satisfies(e -> assertThat(e.getSla()).as("check sla").isEqualTo(actual.getSla()))
            .satisfies(e -> assertThat(e.getTicket()).as("check ticket").isEqualTo(actual.getTicket()));
    }
}
