package com.mycompany.erequest.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TicketSLAAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketSLAAllPropertiesEquals(TicketSLA expected, TicketSLA actual) {
        assertTicketSLAAutoGeneratedPropertiesEquals(expected, actual);
        assertTicketSLAAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketSLAAllUpdatablePropertiesEquals(TicketSLA expected, TicketSLA actual) {
        assertTicketSLAUpdatableFieldsEquals(expected, actual);
        assertTicketSLAUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketSLAAutoGeneratedPropertiesEquals(TicketSLA expected, TicketSLA actual) {
        assertThat(expected)
            .as("Verify TicketSLA auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketSLAUpdatableFieldsEquals(TicketSLA expected, TicketSLA actual) {
        assertThat(expected)
            .as("Verify TicketSLA relevant properties")
            .satisfies(e -> assertThat(e.getDeadline()).as("check deadline").isEqualTo(actual.getDeadline()))
            .satisfies(e -> assertThat(e.getRemindAt()).as("check remindAt").isEqualTo(actual.getRemindAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketSLAUpdatableRelationshipsEquals(TicketSLA expected, TicketSLA actual) {
        assertThat(expected)
            .as("Verify TicketSLA relationships")
            .satisfies(e -> assertThat(e.getTicket()).as("check ticket").isEqualTo(actual.getTicket()));
    }
}
